services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server
    networks:
      - app-network
  auth_service:
    build: auth_service
    volumes:
      - ./auth_service/:./
    ports:
      - 8081:8081
    networks:
      - app-network
    depends_on:
      - redis
    command: ["build/auth_service"]
  api:
    build: api
    volumes:
      - ./api/:./
    ports:
      - 8080:8080
    networks:
      - app-network
    command: ["build/ep_api"]
  algo_service:
    build: algo_service
    ports:
      - 8082:8082
    networks:
      - app-network
    command: ["build/algo_service"]

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
